title: Fahim Ahamed
logo: /Headshot.png
description: AI Research | Machine Learning | Deep Learning | NLP | Computer Vision | Data Science | EDA & Visualization | Big Data | Model Development | Explainable AI | MLOps | Python | TensorFlow | PyTorch | AWS | SQL | Tableau
theme: jekyll-theme-minimal
