title: Fahim Ahamed
logo: /Headshot.png
description: Data Scientist and AI Researcher with expertise in Machine Learning, Deep Learning, NLP, and Computer Vision. Skilled in Python, TensorFlow, PyTorch, SQL, and MLOps, I specialize in predictive modeling, data analysis, and scalable model deployment. My experience spans both industry and research, where I have developed AI-driven solutions for healthcare and cybersecurity.  
theme: jekyll-theme-minimal
