title: Fahim Ahamed
logo: /Headshot.png
# description: Data Scientist and Machine Learning Engineer specializing in predictive modeling, deep learning, NLP, and computer vision. Skilled in TensorFlow, Scikit-learn, SQL, and big data processing, I focus on feature engineering, model optimization, and scalable AI solutions.
theme: jekyll-theme-minimal

email: f.a.tonmoy00@gmail.com
linkedin: https://linkedin.com/in/f-a-tonmoy
google_scholar: https://scholar.google.com/citations?user=qEKKZGMAAAAJ
orcid: https://orcid.org/0009-0006-2638-6521
