title: Fahim Ahamed
logo: /Headshot.png
description: [Email](mailto:f.a.tonmoy00@gmail.com) | [LinkedIn](https://linkedin.com/in/f-a-tonmoy) | [Google Scholar](https://scholar.google.com/citations?user=qEKKZGMAAAAJ) | [ORCID](https://orcid.org/0009-0006-2638-6521)
theme: jekyll-theme-minimal
